# Question 1 : Perceptron Gradient

In [1]:
import pandas as pd
from numpy import *
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('diabetes_PerceptronSVM.csv')

In [3]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
df.shape

(768, 9)

In [5]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [6]:
names = df.columns.tolist()
names_x = names[0:8]
name_y = names[8]

In [7]:
X_df = df[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age',]]
X1=np.array(X_df)
X0 = ones((len(X1),1))
Y = np.array(df[['Outcome']])
X=hstack((X0,X1))

In [8]:
X

array([[  1.   ,   6.   , 148.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,   1.   ,  85.   , ...,  26.6  ,   0.351,  31.   ],
       [  1.   ,   8.   , 183.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  1.   ,   5.   , 121.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   ,   1.   , 126.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,   1.   ,  93.   , ...,  30.4  ,   0.315,  23.   ]])

In [9]:
def sigmoid(x):
    return 1/(1+exp(-x))

In [10]:
def perceptron_gradient(X,Y):
    alpha =1
    iteration =20
    w = zeros(len(X[0]))
    for j in range(iteration):
        for i in range(10):
            w=w+alpha*sigmoid(1-Y[i]*X[i].dot(w))*X[i]*Y[i]
    return w

In [11]:
w=perceptron_gradient(X,Y)
w

array([  0.73105858,   4.38635147, 108.19666964,  52.63621766,
        25.58705025,   0.        ,  24.56356824,   0.45837373,
        36.55292893])

In [12]:
w0=w[0]
w1=w[1]
w2=w[2]
w3=w[3]
w4=w[4]
w5=w[5]
w6=w[6]
w7=w[7]
w8=w[8]
print(w0,w1,w2,w3,w4,w5,w6,w7,w8)

0.7310585786300049 4.38635147178003 108.19666963724073 52.636217661360355 25.587050252050172 0.0 24.563568241968166 0.45837372880101307 36.55292893150025


In [13]:
test=array([1, 0, 185, 142, 70, 85, 31, 0.35, 51])
adjust_test = test.dot(w)
sigmoid(adjust_test)

1.0

## Question 2 : SVM

In [14]:
def svm_gradient(X,Y):
    alpha =1
    iteration =20
    w1 = zeros(len(X[0]))
    for j in range(iteration):
        for i in range(10):
            w1=w1+alpha*sigmoid(1-Y[i]*X[i].dot(w1))*X[i]*Y[i]
    return w1

In [15]:
w1=svm_gradient(X,Y)
w1

array([  0.73105858,   4.38635147, 108.19666964,  52.63621766,
        25.58705025,   0.        ,  24.56356824,   0.45837373,
        36.55292893])

In [16]:
test=array([1, 0, 185, 142, 70, 85, 31, 0.35, 51])
adjust_test = test.dot(w1)
sigmoid(adjust_test)

1.0

# Question 3: KNN

In [17]:

from numpy import *
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd

In [18]:
df_knn = pd.read_csv("diseases_matrix_KNN.csv")
df_knn.head()

Diseases  Fever  Temperature  Hypertension  Blood Pressure  \
0      Hypothermia      0           -1             0             0.0   
1     Hyperthermia      1            2             0             0.0   
2      Hypotension      0            0             0            -1.0   
3  Prehypertension      0            0             1             0.5   
4     Hypertension      0            0             1             1.0   

   Tachycardia  Heart Rate  Tachypnea  Respiration Rate  Hypoxemia  SPO2  \
0            0           0          0                 0          0     0   
1            0           0          0                 0          0     0   
2            0           0          0                 0          0     0   
3            0           0          0                 0          0     0   
4            0           0          0                 0          0     0   

   Headeach  Pain Area  Nausea  GastroInstestinal   
0         0          0       0                   0  
1         0          0       0                   0  
2         0          0       0                   0  
3         0          0       0                   0  
4         0          0       0                   0

In [19]:
from numpy import linalg as LA
x = [1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1]
xx = LA.norm(x[1:])
xx

2.6457513110645907

In [20]:
from numpy import linalg as LA
def my_knn(x,df,k):
    w=[]
    num_red,num_blue=0,0
    winner=''
    for i in range(len(df)):
        coor=df.iloc[i]
        #print(coor[0])
        d = np.sqrt(np.sum(np.subtract(x , coor[1:]).values**2) )
        d = np.dot(1/np.pi,np.arccos(np.divide(np.prod(coor[1:]),LA.norm(coor[1:]))))
        w.append(d)
        w_sorted =argsort(w)[0:k]
        for i in range(len(w_sorted)):
            if(df.iloc[w_sorted[i]][2]=='red'):
                num_red+=1
            else:
                num_blue+=1
                p_red=num_red/len(w_sorted)
                p_blue=num_blue/len(w_sorted)  
                if (p_red>p_blue):
                    winner='red'
                elif (p_blue>p_red):
                    winner='blue'
                else:
                    print('there is tie')
    return winner

# 3 (a)

In [21]:
x = np.array([1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1])
my_knn(x,df_knn,4)

'blue'

# 3 (b)

In [22]:
x1 = np.array([1, 0, 2, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 2])
my_knn(x1,df_knn,4)

'blue'

# 3 (c)

In [23]:
x2 = np.array([1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1])
my_knn(x2,df_knn,4)

'blue'

# Question 4 Naive-Bayes

In [24]:
df_nb=pd.read_csv('Restaurant_reviews_Naive_Bayes.csv')

In [25]:
df_nb.head()

Reviews    Labels
0   Most disgusting food I have ever had  Negative
1        Stay away, very disgusting food  Negative
2  Menu is absolutely perfect, loved it!  Positive
3      A really good value for the money  Positive
4         This is a very good restaurant  Positive

In [26]:
def my_naive_bayes(data, attributes, target):
    
    x=['This was great and not terrible']
    
    def proba(arr,z):
        num_z=0
        for outcome in arr:
            if(outcome==z):
                num_z+=1
        return (num_z+1)/(num_z+len(arr)+1)
    class_value = unique(data[target])
    def conditional_proba(data, attribute, target, class_value, xi):
        arr = data[data[target]==class_value][attribute]
        num_xi=0
        for outcome in arr:
            if (outcome==xi):
                num_xi+=1
        return (num_xi+1)/(num_xi+len(arr)+1)
    
    class_values = unique(data[target])
    
    
    w =[]
    
    for j in range(len(class_value)):
        product_cond_proba_given_class =1
        print(class_value[j])
        proba_for_class = proba(data[target], class_value[j])
        
        print ('P(CD='+class_values[j]+')=', proba_for_class)
        for i in range(len(attributes)):
            
            cond_proba = conditional_proba(data, attributes[i], target, class_value[j], x[i])
            print('P('+attributes[i]+'='+x[i]+'|CD='+class_value[j]+')', cond_proba)
            product_cond_proba_given_class*=cond_proba
            Proba_for_class_given_x=proba_for_class*product_cond_proba_given_class
        w.append(Proba_for_class_given_x)
        print('P(CD='+class_value[j]+'|x=', Proba_for_class_given_x)
    print('\n\nThe Predicted lass is')
    
    return class_value[argmax(w)]

In [27]:
my_naive_bayes(df_nb,['Reviews'],'Labels')

Negative
P(CD=Negative)= 0.2857142857142857
P(Reviews=This was great and not terrible|CD=Negative) 0.16666666666666666
P(CD=Negative|x= 0.047619047619047616
Positive
P(CD=Positive)= 0.4230769230769231
P(Reviews=This was great and not terrible|CD=Positive) 0.09090909090909091
P(CD=Positive|x= 0.038461538461538464


The Predicted lass is


'Negative'